wikipedia:
  language: "vi"
  base_url: "https://vi.wikipedia.org/w/api.php"
  user_agent: "DBPedia-Extractor/1.0"
  rate_limit:
    requests_per_second: 1
    burst_limit: 5
    delay_between_requests: 1.0
  
api:
  format: "json"
  action: "query"
  timeout: 30
  max_retries: 3
  backoff_factor: 2
  
extraction:
  batch_size: 50
  max_articles: 1000
  include_redirects: false
  include_categories: true
  include_infoboxes: true
  include_abstracts: true
  include_content: false
  min_content_length: 100
  
target_categories:
  people:
    - "Thể loại:Danh nhân văn hóa"
    - "Thể loại:Nhân vật lịch sử Việt Nam"
    - "Thể loại:Chính trị gia Việt Nam"
    - "Thể loại:Nhà văn Việt Nam"
    - "Thể loại:Nghệ sĩ Việt Nam"
    - "Thể loại:Nhà khoa học Việt Nam"
  
  places:
    - "Thể loại:Tỉnh thành Việt Nam"
    - "Thể loại:Thành phố Việt Nam"
    - "Thể loại:Di tích lịch sử Việt Nam"
    - "Thể loại:Danh lam thắng cảnh Việt Nam"
  
  organizations:
    - "Thể loại:Trường đại học Việt Nam"
    - "Thể loại:Công ty Việt Nam"
    - "Thể loại:Tổ chức Việt Nam"
  
  events:
    - "Thể loại:Sự kiện lịch sử Việt Nam"
    - "Thể loại:Lễ hội Việt Nam"
  
  works:
    - "Thể loại:Văn học Việt Nam"
    - "Thể loại:Âm nhạc Việt Nam"
    - "Thể loại:Phim Việt Nam"

sample_articles:
  people:
    - "Hồ_Chí_Minh"
    - "Nguyễn_Trãi"
    - "Võ_Nguyên_Giáp"
    - "Phạm_Tuân"
    - "Nguyễn_Du"
    - "Trần_Hưng_Đạo"
    - "Ngô_Quyền"
    - "Lý_Thường_Kiệt"
    - "Nguyễn_Huệ"
    - "Phan_Bội_Châu"
    - "Tôn_Đức_Thắng"
    - "Lê_Duẩn"
    - "Trường_Chinh"
  places:
    - "Hà_Nội"
    - "Thành_phố_Hồ_Chí_Minh"
    - "Huế"
    - "Vịnh_Hạ_Long"
    - "Hội_An"
    - "Quảng_Ninh"
    - "Thanh_Hoá"
  # organizations:
  #   - "Đại_học_Quốc_gia_Hà_Nội"
  #   - "Đại_học_Bách_khoa_Hà_Nội"
  #   - "Đại_học_Quốc_gia_Thành_phố_Hồ_Chí_Minh"
  # events:
  #   - "Chiến_thắng_Điện_Biên_Phủ"
  #   - "Cách_mạng_tháng_Tám"
  # works:
  #   - "Truyện_Kiều"
  #   - "Số_đỏ"
  #   - "Dế_Mèn_phiêu_lưu_ký"